language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false

git:
    submodules: true

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src/homie-sht30.ino

install:
    - pip install -U platformio
    - platformio lib -g install 252 555

script:
    - platformio ci --board=esp01_1m
